version: "3.2"
services:
    flask:
        container_name: flask-server
    sql-server-db:
        container_name: sql-server-db
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "change_this_password"
            ACCEPT_EULA: "Y"